### ISSUE TITLE
config example

### ISSUE THREAD

**Issue by zhnxin** [zhnxin/rn_spider#1]

**Comment by zhnxin** [comment]
# soshuw.toml
```toml
url_list = [
  "14169702",
]
base = 'https://m.soshuwu.com'
content = 'div.content'
next = '#chapter> div.pager> a:nth-child(3)'
next_regexp = '.html'
title = 'h1.headline'
```
